version: '2'
services:

  db:
    image: postgres:alpine
    volumes:
      - ./db:/var/lib/postgresql/data/pgdata
    ports:
      - "5432"

  web:
    build: ./docker/dev
    image: web-dev
    volumes:
      - ./:/app
    command: mix phoenix.server
    ports:
      - "4000:4000"
    depends_on:
      - db
